//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_CoffeeShop.Utilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int id { get; set; }
        public Nullable<int> idAccount { get; set; }
        public string address1 { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
