//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_CoffeeShop.Utilities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CoffeeShopSystemEntities : DbContext
    {
        public CoffeeShopSystemEntities()
            : base("name=CoffeeShopSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CommentBlog> CommentBlogs { get; set; }
        public virtual DbSet<Discount> Discounts { get; set; }
        public virtual DbSet<ForgotPassword> ForgotPasswords { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<InvoiceAdmin> InvoiceAdmins { get; set; }
        public virtual DbSet<InvoiceDetail> InvoiceDetails { get; set; }
        public virtual DbSet<InvoiceSupplier> InvoiceSuppliers { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<SupplierRefundV> SupplierRefundVs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserNewEmail> UserNewEmails { get; set; }
        public virtual DbSet<Voucher> Vouchers { get; set; }
        public virtual DbSet<W_RegisterAccount> W_RegisterAccount { get; set; }
        public virtual DbSet<W_RegisterSupplier> W_RegisterSupplier { get; set; }
        public virtual DbSet<W_SHandleInvoice> W_SHandleInvoice { get; set; }
        public virtual DbSet<WatchList> WatchLists { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
    
        public virtual ObjectResult<int> Comment_MaxIndC(Nullable<int> mnC, Nullable<int> idBlog)
        {
            var mnCParameter = mnC.HasValue ?
                new ObjectParameter("mnC", mnC) :
                new ObjectParameter("mnC", typeof(int));
    
            var idBlogParameter = idBlog.HasValue ?
                new ObjectParameter("idBlog", idBlog) :
                new ObjectParameter("idBlog", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<int>("Comment_MaxIndC", mnCParameter, idBlogParameter);
        }
    
        public virtual ObjectResult<Comment_MnC_Type_Result> Comment_MnC_Type(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Comment_MnC_Type_Result>("Comment_MnC_Type", idParameter);
        }
    
        public virtual ObjectResult<Comment_SubC_Type_Result> Comment_SubC_Type(Nullable<int> idBlog, Nullable<int> idMnC)
        {
            var idBlogParameter = idBlog.HasValue ?
                new ObjectParameter("idBlog", idBlog) :
                new ObjectParameter("idBlog", typeof(int));
    
            var idMnCParameter = idMnC.HasValue ?
                new ObjectParameter("idMnC", idMnC) :
                new ObjectParameter("idMnC", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Comment_SubC_Type_Result>("Comment_SubC_Type", idBlogParameter, idMnCParameter);
        }
    
        public virtual ObjectResult<GetCommentMain_Result> GetCommentMain(Nullable<int> idCmt)
        {
            var idCmtParameter = idCmt.HasValue ?
                new ObjectParameter("idCmt", idCmt) :
                new ObjectParameter("idCmt", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCommentMain_Result>("GetCommentMain", idCmtParameter);
        }
    
        public virtual ObjectResult<GetCommentSub_Result> GetCommentSub(Nullable<int> idSubC)
        {
            var idSubCParameter = idSubC.HasValue ?
                new ObjectParameter("idSubC", idSubC) :
                new ObjectParameter("idSubC", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCommentSub_Result>("GetCommentSub", idSubCParameter);
        }
    }
}
