//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_CoffeeShop.Utilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentBlog
    {
        public int id { get; set; }
        public Nullable<int> idBlog { get; set; }
        public string idAccount { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> dateCreate { get; set; }
        public int indC { get; set; }
        public Nullable<int> mnC { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> userType { get; set; }
    
        public virtual Blog Blog { get; set; }
    }
}
