//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_CoffeeShop.Utilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        public int id { get; set; }
        public Nullable<decimal> discount1 { get; set; }
        public Nullable<System.DateTime> dateBegin { get; set; }
        public Nullable<System.DateTime> dateEnd { get; set; }
        public Nullable<int> idProduct { get; set; }
        public Nullable<int> isStatus { get; set; }
        public Nullable<int> indC { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
