//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_CoffeeShop.Utilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceAdmin
    {
        public int id { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> idInvoice { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<decimal> feeService { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
