//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_CoffeeShop.Utilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.InvoiceAdmins = new HashSet<InvoiceAdmin>();
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
            this.InvoiceSuppliers = new HashSet<InvoiceSupplier>();
        }
    
        public int id { get; set; }
        public Nullable<int> idAccount { get; set; }
        public string address { get; set; }
        public Nullable<decimal> totalPrice { get; set; }
        public string idPayment { get; set; }
        public string idVoucherS { get; set; }
        public string idVoucherA { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> isStatus { get; set; }
        public string codeInvoice { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceAdmin> InvoiceAdmins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceSupplier> InvoiceSuppliers { get; set; }
    }
}
