//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_CoffeeShop.Utilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int id { get; set; }
        public Nullable<int> idAccount { get; set; }
        public Nullable<int> idProduct { get; set; }
        public Nullable<int> review1 { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> invoiceDetail { get; set; }
        public string content1 { get; set; }
    }
}
