//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_CoffeeShop.Utilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNewEmail
    {
        public int id { get; set; }
        public string email { get; set; }
        public Nullable<int> userType { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<long> timeMils { get; set; }
        public string keyAccept { get; set; }
    }
}
