//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_CoffeeShop.Utilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public string id { get; set; }
        public Nullable<decimal> condition { get; set; }
        public Nullable<int> discount { get; set; }
        public string usercreate { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<int> isActive { get; set; }
        public Nullable<int> used { get; set; }
        public int idenVou { get; set; }
    }
}
