//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_CoffeeShop.Utilities
{
    using System;
    using System.Collections.Generic;
    
    public partial class W_SHandleInvoice
    {
        public int id { get; set; }
        public Nullable<int> idInvoice { get; set; }
        public Nullable<int> idInvoiceD { get; set; }
        public Nullable<int> idSupplier { get; set; }
        public Nullable<int> statusCase { get; set; }
    }
}
